# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

name = "momoka"
version = "1.0.1"
gleam = ">= 0.2.1"
description = "Gemini-to-Gopher Proxy"
licenses = ["GPL-3.0-only"]
repository = { type = "github", user = "Fuwn", repo = "momoka" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glisten = ">= 3.0.0 and < 4.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
envoy = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
